---
tap_install:
  values:
    profile: full # Can take iterate, build, run, view.
    supply_chain: basic # Can take testing, testing_scanning.
    ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

    excluded_packages:
    - learningcenter.tanzu.vmware.com
    - workshops.learningcenter.tanzu.vmware.com


    shared:
      ingress_domain: "tapv6.tanzucld.xyz"
      # ingress_issuer: # Optional, can denote a cert-manager.io/v1/ClusterIssuer of your choice. Defaults to "tap-ingress-selfsigned".
    
      image_registry:
        project_path: "tanzu01.azurecr.io/1.6.x/supply-chain"
        secret:
          name: "registry-credentials"
          namespace: "tap-install"
    
    #Below are the keys which may have default values set, but can be overridden.
    ootb_supply_chain_basic: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
      gitops:
        ssh_secret: "" # Takes "" as value by default; but can be overridden by setting a different value.
    
    contour:
      envoy:
        service:
          type: LoadBalancer # This is set by default, but can be overridden by setting a different value.
    
    buildservice:
      kp_default_repository: "tanzu01.azurecr.io/tap-1.6.x/aks/build-service"
    
    local_source_proxy:
      # Takes the value from the project_path under the image_registry section of shared by default, but can be overridden by setting a different value.
      repository: "tanzu01.azurecr.io/tap-1.6.x/local-source"
      push_secret:
        # When set to true, the secret mentioned in this section is automatically exported to Local Source Proxy's namespace.
        name: "lsp-push-credentials"
        namespace: "tap-install"
        # When set to true, the secret mentioned in this section is automatically exported to Local Source Proxy's namespace.
        create_export: true
    
    tap_gui:
      metadataStoreAutoconfiguration: true # Creates a service account, the Kubernetes control plane token and the requisite app_config block to enable communications between Tanzu Developer Portal and SCST - Store.
      ingressEnabled: "true"
      app_config:
        auth:
          allowGuestAccess: true  # This allows unauthenticated users to log in to your portal. If you want to deactivate it, make sure you configure an alternative auth provider.
        # catalog:
        #   locations:
        #     - type: url
        #       target: https://GIT-CATALOG-URL/catalog-info.yaml
    
    metadata_store:
      ns_for_export_app_cert: "*" # Verify this namespace is available within your cluster before initiating the Tanzu Application Platform installation.
      app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.
    
    scanning:
      metadataStore:
      # In a single cluster, the connection between the scanning pod and the metadata store happens inside the cluster and does not pass through ingress. This is automatically configured, you do not need to provide an ingress connection to the store.
        url: "" # Configuration is moved, so set this string to empty.
    
    policy:
      tuf_enabled: false # By default, TUF initialization and keyless verification are deactivated.
    
    ## namespace provisioner block
    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/master
        subPath: clusters/mytap/cluster-config/ns-provisioner/namespaces
        url: https://github.com/berinle/tap-gitops
      additional_sources:
        - git:
            ref: origin/master
            subPath: clusters/mytap/cluster-config/ns-provisioner/ns-resources
            url: https://github.com/berinle/tap-gitops
          path: _ytt_lib/ns-resources
      # default_parameters:
        # supply_chain_service_account:
        #   secrets:
        #     - git-https
        #   imagePullSecrets: [] # optional